### ISSUE TITLE
Extra Config creation is dead code

### ISSUE THREAD

**Issue by chrisjohnson16** [datastax/pulsar_workshop#12]
The code in both NatProdCmdApp and NatConsCmdApp that creates the extra configuration variable is dead code.  The extraCfgConf variable is created and set to null, but then the variable is only instantiated if it's not null.  The code is linked here -

https://github.com/datastax/pulsar_workshop/blob/e26e45fc5795f55011c3058c9324ec8cce6043aa/application_code/client_apps/java/nat_cons/src/main/java/com/example/pulsarworkshop/nat_cons/NatConsCmdApp.java#L118

Removing the conditional check results in NPE - 

Exception in thread "main" java.lang.NullPointerException: Cannot invoke "java.io.File.getCanonicalPath()" because "extraCfgFile" is null
	at com.example.pulsarworkshop.common.PulsarExtraCfgConf.readRawCfgFromFile(PulsarExtraCfgConf.java:77)
	at com.example.pulsarworkshop.common.PulsarExtraCfgConf.<init>(PulsarExtraCfgConf.java:55)
	at com.example.pulsarworkshop.common.PulsarWorkshopCmdApp.createNativePulsarClient(PulsarWorkshopCmdApp.java:135)
	at com.example.pulsarworkshop.nat_cons.NatConsCmdApp.runApp(NatConsCmdApp.java:111)
	at com.example.pulsarworkshop.nat_cons.NatConsCmdApp.main(NatConsCmdApp.java:48)

**Comment by yabinmeng** [comment]
createNativePulsarClient() method is expecting client.conf file, not the extra config file. It looks like you're passing the wrong file.
See this line: https://github.com/datastax/pulsar_workshop/blob/e26e45fc5795f55011c3058c9324ec8cce6043aa/application_code/client_apps/java/nat_cons/src/main/java/com/example/pulsarworkshop/nat_cons/NatConsCmdApp.java#L124

it is expecting `connCfgConf`, not `extraCfgConf`

`pulsarClient = createNativePulsarClient(connCfgConf);`
